import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillGithub, AiFillLinkedin, AiFillInstagram} from "react-icons/ai";
import Image from "next/image";
import avatar from '../pages/myavatar.JPG';
import { useParallax } from 'react-scroll-parallax';
import React, { useRef } from "react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
        
      </Head>
      <main className="bg-black px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-xl text-teal-400">MyHomePage</h1>
            <ul className=" flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl " />
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >Contact
                </a>
              </li>
            </ul>   
          </nav>
          <div className="flex justify-center items-center">
            <div className="text-5xl flex-col fixed top-64 left-0 gap-4 py-3 text-white">
              <div className="bg-red-700"><a href="#" ><AiFillInstagram /></a></div>
              <div className="bg-blue-600"><a href="#" ><AiFillLinkedin /></a></div>
              <div className="bg-gray-700"><a href="#"><AiFillGithub /></a></div>
            </div>
            <Image className="outline-teal-400 rounded-full h-56 w-64" src={avatar}/>
          </div>
          <div className="text-center p-10">
            <h2 className="text-6xl py-2 text-teal-600 font-medium">Daeen Kabir</h2>
            <h3 className="text-3xl py-2 text-yellow-600">Frontend Developer and ML engineer</h3>
            <p className="font-sans text-lg py-5 leading-8 text-white">
              Frontend web developer with knowledge on HTML, CSS, CSS Tailwind, Bootstrap, and aspiring ML engineer with knowledge in machine and deep learning algorithms and PyTorch.
            </p>
          </div>
        </section>
        <br/>
        <section className="h-screen">
          <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-red flex-1">
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-white py-1">Figma</p>
          </div>
        </section>
      </main>
    </div>
  );
}

